version: '3'
services:
  fastapi:
    build: .
    restart: "always"
    volumes:
    - ./:/app
    working_dir: /app
    ports:
      - "8001:8001"
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8001
  frontend:
    build: ./frontend
    restart: "always"
    volumes:
    - ./frontend:/app
    working_dir: /app
    ports:
      - "3000:3000"
    command: npm install && npm start